### ISSUE TITLE
Windows10 install failed

### ISSUE THREAD

**Issue by jzy2000** [mike-goodwin/owasp-threat-dragon-desktop#94]
I tried to install on win10 64bit by running `npm install`, encounter errors, please advise:

```
> electron@5.0.5 postinstall C:\Users\xyz\Desktop\owasp-threat-dragon-desktop-master\node_modules\electron
> node install.js

Downloading tmp-2016-0-electron-v5.0.5-win32-x64.zip
Error: unable to get local issuer certificate
C:\Users\xyz\Desktop\owasp-threat-dragon-desktop-master\node_modules\electron\install.js:49
  throw err
  ^

Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1473:34)
    at TLSSocket.emit (events.js:311:20)
    at TLSSocket._finishInit (_tls_wrap.js:916:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:686:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-xattr@0.3.0 (node_modules\fs-xattr):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fs-xattr@0.3.0: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: electron-installer-redhat@2.0.0 (node_modules\electron-installer-redhat):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for electron-installer-redhat@2.0.0: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: electron-installer-debian@2.0.1 (node_modules\electron-installer-debian):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for electron-installer-debian@2.0.1: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: macos-alias@0.2.11 (node_modules\macos-alias):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for macos-alias@0.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: appdmg@0.6.0 (node_modules\appdmg):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.6.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@5.0.5 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@5.0.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xyz\AppData\Roaming\npm-cache\_logs\2020-02-28T20_16_19_366Z-debug.log```

**Comment by jgadsden** [comment]
Hello @jzy2000 - could you try the version 1.0 Windows installer from : 
https://github.com/mike-goodwin/owasp-threat-dragon-desktop/releases/download/v1.0/OWASP-Threat-DragonSetup.exe
which should get you up and running for the moment.
I have double checked install using `npm install` on my Windows 10 machine and it works as expected. Could you try installing again to rule out any temporary download issues?
Also, could you check your npm version with `npm --version` , for example mine is 6.13.4

**Comment by jzy2000** [comment]
Thanks for suggestion, the installer works fine.
I have identical npm installed.

**Comment by jgadsden** [comment]
I think the error thrown on `node install.js` may be a known issue on some Windows systems:
https://github.com/npm/npm/issues/9969
@jzy2000 can you try `npm install phantom --save` and then `npm install`
